creating json
navgurukul/newton pull request #159
Opened 2021-09-08 14:58 UTC by muskan9650

2021-09-08 15:02 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "component": "Code block",
Replace "Code Block" with just "code"

2021-09-08 15:03 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "type": "Javascript",
Please understand that "Javascript" != "javascript". Things like this should not be in title case. Make it in all small

2021-09-08 15:04 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "Text": "if (condition is true) {statement is executed}"
Where in the sample json file you found `Text` key instead of `text` key

2021-09-08 15:10 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "Text": "if (condition is true) {statement is executed}"
Please make it `text`. Keys are important. Client would never be able to find `something.Text`

2021-09-08 15:10 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "component": "Block quote",
no space in between and all small

2021-09-08 15:11 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "value": "**Note**",
If you already defined `bold` in decoration. No need to give ** ** in value. Just give the text

2021-09-08 15:11 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "value": ": These conditions are known as Boolean conditions and they are only be true or false.\n"
Where is the opening "?

2021-09-08 15:16 UTC, pysaquib requested changes

2021-09-08 15:16 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "component": "Block quote",
blockquote

2021-09-08 15:16 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "component": "Block quote",
blockquote

2021-09-08 15:16 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "value": "**Example**",
remove **

2021-09-08 15:16 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "component": "Code block ",
code

2021-09-08 15:16 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "type": "Javascript",
javascript

2021-09-08 15:16 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "Text": "var a = 10; var b = 12; if(b > a){ console.log( b,' is greater than  ', a  );}"
text

2021-09-08 15:16 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "value": "**Example**",
Also after Example there was `:-`
Make a new json obj for it. type will be text

2021-09-08 15:16 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +        "component": "H3",
component is `header`
variant is `3`
Check the sample file `js-intro_json` for reference

2021-09-08 15:16 UTC, pysaquib commented on js-if-else_json/if-Statement.json
> +]
Press enter after this line

2021-09-08 15:32 UTC, muskan9650 commented on js-if-else_json/if-Statement.json
> +        "value": ": These conditions are known as Boolean conditions and they are only be true or false.\n"
the opening inverted comma is between the colons :  ":

2021-09-09 11:44 UTC, pysaquib commented on js-if-else_json/conditional-statements.json
> +        "component": "code ",
extra space after `code`

2021-09-09 11:45 UTC, pysaquib commented on js-if-else_json/else-Statement.json
> +        "component": "code ",
space

2021-09-09 11:46 UTC, pysaquib requested changes
fix

2021-09-09 11:47 UTC, pysaquib commented on js-if-else_json/index.md
> +- conditional-statements.md
Will it be `.md`?

2021-09-09 11:48 UTC, pysaquib requested changes
fix this

2021-09-09 13:26 UTC, merged